# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="neon-nexus"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git rtm-reminder-zsh)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# fnm (Node.js version manager)
FNM_PATH="/home/sarah/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
fi

# Core aliases
alias ls='ls --color=auto'
alias vi="vim"
alias discord='discordo'
alias signal="gurk"
alias spotify="ncspot"
alias steam="sudo sysctl kernel.split_lock_mitigate=0 && prime-run steam; sudo sysctl kernel.split_lock_mitigate=1";
alias test-notifications="~/.config/test-notifications.sh"
alias rtm="/home/sarah/code/rtm-cli/bin/rtm"
alias sf6="sudo sysctl kernel.split_lock_mitigate=0 && prime-run steam steam://rungameid/1364780; sudo sysctl kernel.split_lock_mitigate=1"
alias cyberpunk="sudo sysctl kernel.split_lock_mitigate=0 && prime-run steam steam://rungameid/1091500; sudo sysctl kernel.split_lock_mitigate=1"
alias windows="cd /mnt/windows/Users/arane"

# Initialize zoxide
eval "$(zoxide init zsh)"

# fzf fuzzy finder
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# Less with color support
export LESS="-R"

# Qt theming for Dolphin
export QT_STYLE_OVERRIDE=kvantum

# Dolphin alias with theming
alias dolphin='QT_STYLE_OVERRIDE=kvantum /usr/bin/dolphin'
export LOCAL_DEV=true
alias melchior='melchior-connect-script'
alias melchior-update-hosts='melchior-update-hosts-script'
alias mbash='ssh melchior'
alias gwa='ssh -t melchior "cd /mnt/data/opt/gwa && zsh"'
alias centera-db-local="mysql -h 127.0.0.1 -P 3307 -u centera_dev -pcentera_dev_password centera"
alias centera-db-prod="mysql -h 165.232.57.205 -u root -pePaMfK6xwk5xAJgbflkQ --ssl-verify-server-cert=false centera"  
alias centera-prod="ssh root@centera-prod-web-01"
alias centera-dev="ssh root@centera-dev-web-01"
alias centera-bnsf-import="ssh root@centera-bnsf-import"
alias centera-bnsf-trace="ssh root@centera-bnsf-trace"
alias centera-csx-trace="ssh root@centera-csx-trace"
alias centera-schneider-bot="ssh root@centera-schneider-bot"
alias centera-ns-import="ssh root@centera-ns-import"
alias centera-cp-import="ssh root@centera-cp-import"
alias centera-cn-trace="ssh root@centera-cn-trace"
alias centera-ns-trace="ssh root@centera-ns-trace"

